---
deployment:
      tasks:
        - export DEPLOYPATH=/home/natclwow/repositories/todolist-v2
        - /bin cp * $DEPLOYPATH 
        - /bin cp /views/* $DEPLOYPATH
        - /bin cp /public/css/* $DEPLOYPATH
